- name: create home bin folder
  command: mkdir ~/bin creates=~/bin

- name: get delete-merged
  get_url: url=https://gist.github.com/renanivo/4990090/raw/7b3d5ab9e396a0ab7b23f288da79eb41798c67ef/delete-merged.sh
           dest=~/bin/delete-merged

- name: make delete-merged executable
  file: path=~/bin/delete-merged mode=0540

- name: install GNU sed
  homebrew: name=gnu-sed state=present

- name: install rbenv
  homebrew: name=rbenv state=present

- name: install ruby-build
  homebrew: name=ruby-build state=present

- name: get composer
  shell: cd ~/bin; curl -sS https://getcomposer.org/installer | php creates=~/bin/composer

- name: remove .phar from composer
  shell: mv ~/bin/composer.phar ~/bin/composer creates=~/bin/composer

- name: get twig-lint
  command: wget http://asm89.github.com/d/twig-lint.phar chdir=~/bin creates=~/bin/twig-lint

- name: remove .phar from twig-lint
  shell: mv ~/bin/twig-lint.phar ~/bin/twig-lint creates=~/bin/twig-lint

- name: make twig-lint executable
  file: path=~/bin/twig-lint mode=0540

- name: get php-tools
  git: repo=git@github.com:EHER/php-tools.git dest=~/.php-tools
  notify:
    - compose php-tools
    - execute PHPCS set PSR-2
