- name: ensure there's a bin folder into the home folder
  command: mkdir ~/bin creates=~/bin

- name: ensure delete-merged script is present
  get_url: url=https://gist.github.com/renanivo/4990090/raw/7b3d5ab9e396a0ab7b23f288da79eb41798c67ef/delete-merged.sh
           dest=~/bin/delete-merged

- name: ensure delete-merged script is executable
  file: path=~/bin/delete-merged mode=0540

- name: ensure GNU sed is installed
  homebrew: name=gnu-sed state=present

- name: ensure fish shell is installed
  homebrew: name=fish state=present
  notify:
    - add fish to shells
    - set fish as default shell

- name: create fish configuration directory
  file: path=~/.config/fish state=directory

- name: ensure fish configuration is updated
  copy: src=config.fish dest=~/.config/fish/config.fish
